ksql_listener_port: 8088

ksql:
  config_file: /etc/ksql/ksql-server.properties
  service_name: confluent-ksql
  systemd_override: /etc/systemd/system/confluent-ksql.service.d
  user: cp-ksql
  group: confluent
  environment:
    KSQL_HEAP_OPTS: "-Xmx3g"
  config:
    application.id: ksql-server
    listeners: http://0.0.0.0:{{ksql_listener_port}}
    ssl.endpoint.identification.algorithm: ""
  systemd:
    enabled: yes
    state: started
