- name: create ssl certificate directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
- name: create ssl certs
  script: scripts/certs-create.sh
  args:
    chdir: /var/ssl/private
    creates: /var/ssl/private/broker.keystore.jks
- name: copy ssl related files to local ansible host
  synchronize:
    src: /var/ssl/private/
    dest: generated_ssl_files
    mode: pull
