kafkarest:
  user: cp-kafka-rest
  group: confluent
  config_file: /etc/kafka-rest/kafka-rest.properties
  service_name: confluent-kafka-rest
  systemd_override: /etc/systemd/system/confluent-kafka-rest.service.d
  config:
    listeners: http://0.0.0.0:8082
    client.ssl.endpoint.identification.algorithm: ""
  environment:
    LOG_DIR: /var/log/kafka-rest
  systemd:
    enabled: yes
    state: started
