- hosts: preflight
  tasks:
  - import_role:
      name: confluent.preflight
    tags:
      - pre-install
- hosts: ssl_CA
  tasks:
  - import_role:
      name: confluent.ssl_CA
    tags:
      - pre-install
- hosts: zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper
- hosts: broker
  tasks:
  - import_role:
      name: confluent.kafka-broker
- hosts: schema-registry
  tasks:
  - import_role:
      name: confluent.schema-registry
- hosts: connect-distributed
  tasks:
  - import_role:
      name: confluent.connect-distributed
- hosts: ksql
  tasks:
  - import_role:
      name: confluent.ksql
- hosts: control-center
  tasks:
  - import_role:
      name: confluent.control-center
- hosts: kafka-rest
  tasks:
  - import_role:
      name: confluent.kafka-rest
- hosts: tools
  tasks:
  - import_role:
      name: confluent.tools
    tags:
      - post-install
