- name: ksql create group
  group:
    name: "{{ksql.group}}"
- name: ksql create user
  user:
    name: "{{ksql.user}}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{ksql.group}}"
- name: ksql create config
  template:
    src: ksql.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart ksql
- name: ksql create config
  template:
    src: ksql_ssl.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: security_mode == "ssl"
  notify:
    - restart ksql
- name: ksql create config
  template:
    src: ksql_sasl_ssl.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart ksql
- name: create systemd override file
  file:
    path: "{{ksql.systemd_override}}"
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
    state: directory
    mode: 0640
- name: write environment variables
  template:
    src: environment.j2
    dest: "{{ksql.systemd_override}}/override.conf"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  notify:
    - reload systemd
    - restart ksql
- name: ksql configure service
  systemd:
    name: "{{ksql.service_name}}"
    enabled: "{{ksql.systemd.enabled}}"
    state: "{{ksql.systemd.state}}"    
