all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: sasl_ssl
preflight:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
    ip-172-31-5-30.us-east-2.compute.internal:
    ip-172-31-10-0.us-east-2.compute.internal:
    ip-172-31-12-225.us-east-2.compute.internal:
ssl_CA:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
zookeeper:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
    ip-172-31-5-30.us-east-2.compute.internal:
    ip-172-31-10-0.us-east-2.compute.internal:
broker:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
      kafka:
        broker:
          id: 1
    ip-172-31-5-30.us-east-2.compute.internal:
      kafka:
        broker:
          id: 2
    ip-172-31-10-0.us-east-2.compute.internal:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
control-center:
  hosts:
    ip-172-31-12-225.us-east-2.compute.internal:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ip-172-31-10-207.us-east-2.compute.internal:8083
connect-distributed:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
kafka-rest:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
ksql:
  hosts:
    ip-172-31-5-30.us-east-2.compute.internal:
